# Generated by Django 4.2.17 on 2025-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="docs",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
